name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10


      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - run: pnpm --version && node -v && pnpm exec nx report
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Diagnostic step: build the specific app with verbose logs and no cache
      - run: NX_CACHE=false pnpm exec nx build auth --configuration=production --skip-nx-cache --verbose
        env:
          NODE_ENV: production

      # Print versions of key webpack loaders/plugins to catch mismatches
      - run: pnpm ls webpack css-loader sass sass-loader mini-css-extract-plugin postcss postcss-loader dotenv-webpack @angular-devkit/build-angular @ngtools/webpack || true

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: pnpm exec nx affected -t lint test build e2e
        env:
          NODE_ENV: production
